.PHONY: install
install:
	@cd turbo && go install
	@cd protoc-gen-buildfields && go install

.PHONY: test
test:
	@go test -p=1 -cover -coverpkg github.com/vaporz/turbo github.com/vaporz/turbo github.com/vaporz/turbo/test
	@cd test/testcreateservice && go build ./...
	@cd test/testservice && go build ./...

.PHONY: doc
doc:
	@cd doc && make html

# govulncheck answers a different question from the dependency list: which known
# vulnerabilities this code can actually reach. It reads the vulnerability database
# over the network, so it is deliberately not part of "make test", which has to
# work offline.
#
# It scans the packages by name rather than "./...": test/testcreateservice is
# generated by the test run and a failed run can leave it half written, and a
# vulnerability scan should not depend on that.
.PHONY: vuln
vuln:
	@command -v govulncheck >/dev/null 2>&1 || { \
		echo "govulncheck not found, install it with:"; \
		echo "  go install golang.org/x/vuln/cmd/govulncheck@latest"; \
		exit 1; }
	@govulncheck github.com/vaporz/turbo github.com/vaporz/turbo/test

.PHONY: fmt
fmt:
	@gofmt -w *.go protoc-gen-buildfields/*.go test/*.go turbo/*.go turbo/cmd/*.go
