.PHONY: install
install:
	@cd turbo && go install
	@cd protoc-gen-buildfields && go install

.PHONY: test
test:
	@go test -p=1 -cover -coverpkg github.com/vaporz/turbo github.com/vaporz/turbo github.com/vaporz/turbo/test
	@cd test/testcreateservice && go build ./...
	@cd test/testservice && go build ./...

# The tutorials are plain markdown, so there is nothing to build: point at the index.
# (This used to run "make html" in ./doc, a sphinx tree that is not part of this
# repository.)
.PHONY: doc
doc:
	@echo "Turbo documentation: docs/README.md (start there, it links the rest)"

# The integration tests generate test/testcreateservice and leave it behind. It is
# part of this module, so "go mod tidy" counts what it imports, and a dependency
# that only the generated tree still uses is classified as direct -- which flips
# depending on whether the tests have run. Clear it first, so the answer is the
# same every time.
.PHONY: clean-gen
clean-gen:
	@rm -rf test/testcreateservice

.PHONY: tidy
tidy: clean-gen
	@go mod tidy

# govulncheck answers a different question from the dependency list: which known
# vulnerabilities this code can actually reach. It reads the vulnerability database
# over the network, so it is deliberately not part of "make test", which has to
# work offline.
#
# It scans the packages by name rather than "./...": test/testcreateservice is
# generated by the test run and a failed run can leave it half written, and a
# vulnerability scan should not depend on that.
.PHONY: vuln
vuln:
	@command -v govulncheck >/dev/null 2>&1 || { \
		echo "govulncheck not found, install it with:"; \
		echo "  go install golang.org/x/vuln/cmd/govulncheck@latest"; \
		exit 1; }
	@govulncheck github.com/vaporz/turbo github.com/vaporz/turbo/test

.PHONY: fmt
fmt:
	@gofmt -w *.go protoc-gen-buildfields/*.go test/*.go turbo/*.go turbo/cmd/*.go
