// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        (unknown)
// source: testprotos.proto

package turbo

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TestPrimitives struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Int64Value   int64   `protobuf:"varint,1,opt,name=Int64Value,json=int64Value,proto3" json:"Int64Value,omitempty"`
	Int32Value   int32   `protobuf:"zigzag32,2,opt,name=Int32Value,json=int32Value,proto3" json:"Int32Value,omitempty"`
	Uint64Value  uint64  `protobuf:"varint,3,opt,name=Uint64Value,json=uint64Value,proto3" json:"Uint64Value,omitempty"`
	Uint32Value  uint32  `protobuf:"varint,4,opt,name=Uint32Value,json=uint32Value,proto3" json:"Uint32Value,omitempty"`
	Float32Value float32 `protobuf:"fixed32,5,opt,name=Float32Value,json=float32Value,proto3" json:"Float32Value,omitempty"`
	Float64Value float64 `protobuf:"fixed64,6,opt,name=Float64Value,json=float64Value,proto3" json:"Float64Value,omitempty"`
	BoolValue    bool    `protobuf:"varint,7,opt,name=BoolValue,json=boolValue,proto3" json:"BoolValue,omitempty"`
}

func (x *TestPrimitives) Reset() {
	*x = TestPrimitives{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testprotos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestPrimitives) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestPrimitives) ProtoMessage() {}

func (x *TestPrimitives) ProtoReflect() protoreflect.Message {
	mi := &file_testprotos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestPrimitives.ProtoReflect.Descriptor instead.
func (*TestPrimitives) Descriptor() ([]byte, []int) {
	return file_testprotos_proto_rawDescGZIP(), []int{0}
}

func (x *TestPrimitives) GetInt64Value() int64 {
	if x != nil {
		return x.Int64Value
	}
	return 0
}

func (x *TestPrimitives) GetInt32Value() int32 {
	if x != nil {
		return x.Int32Value
	}
	return 0
}

func (x *TestPrimitives) GetUint64Value() uint64 {
	if x != nil {
		return x.Uint64Value
	}
	return 0
}

func (x *TestPrimitives) GetUint32Value() uint32 {
	if x != nil {
		return x.Uint32Value
	}
	return 0
}

func (x *TestPrimitives) GetFloat32Value() float32 {
	if x != nil {
		return x.Float32Value
	}
	return 0
}

func (x *TestPrimitives) GetFloat64Value() float64 {
	if x != nil {
		return x.Float64Value
	}
	return 0
}

func (x *TestPrimitives) GetBoolValue() bool {
	if x != nil {
		return x.BoolValue
	}
	return false
}

type TestProtoStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=Value,json=value,proto3" json:"Value,omitempty"`
}

func (x *TestProtoStruct) Reset() {
	*x = TestProtoStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testprotos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestProtoStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestProtoStruct) ProtoMessage() {}

func (x *TestProtoStruct) ProtoReflect() protoreflect.Message {
	mi := &file_testprotos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestProtoStruct.ProtoReflect.Descriptor instead.
func (*TestProtoStruct) Descriptor() ([]byte, []int) {
	return file_testprotos_proto_rawDescGZIP(), []int{1}
}

func (x *TestProtoStruct) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type TestTags struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *TestTagsData `protobuf:"bytes,1,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
}

func (x *TestTags) Reset() {
	*x = TestTags{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testprotos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestTags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTags) ProtoMessage() {}

func (x *TestTags) ProtoReflect() protoreflect.Message {
	mi := &file_testprotos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTags.ProtoReflect.Descriptor instead.
func (*TestTags) Descriptor() ([]byte, []int) {
	return file_testprotos_proto_rawDescGZIP(), []int{2}
}

func (x *TestTags) GetData() *TestTagsData {
	if x != nil {
		return x.Data
	}
	return nil
}

type TestTagsData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UploadFile       string  `protobuf:"bytes,1,opt,name=UploadFile,json=uploadFile,proto3" json:"UploadFile,omitempty"`
	UploadUrl        string  `protobuf:"bytes,2,opt,name=UploadUrl,json=uploadUrl,proto3" json:"UploadUrl,omitempty"`
	MetadataOnly     string  `protobuf:"bytes,3,opt,name=MetadataOnly,json=metadataOnly,proto3" json:"MetadataOnly,omitempty"`
	ContentTypeId    int64   `protobuf:"varint,4,opt,name=ContentTypeId,json=contentTypeId,proto3" json:"ContentTypeId,omitempty"`
	CreativeApiId    int64   `protobuf:"varint,5,opt,name=CreativeApiId,json=creativeApiId,proto3" json:"CreativeApiId,omitempty"`
	Duration         int32   `protobuf:"zigzag32,6,opt,name=Duration,json=duration,proto3" json:"Duration,omitempty"`
	PhysicalDuration float32 `protobuf:"fixed32,7,opt,name=PhysicalDuration,json=physicalDuration,proto3" json:"PhysicalDuration,omitempty"`
	Bitrate          int32   `protobuf:"zigzag32,8,opt,name=Bitrate,json=bitrate,proto3" json:"Bitrate,omitempty"`
	Height           int32   `protobuf:"zigzag32,9,opt,name=Height,json=height,proto3" json:"Height,omitempty"`
	Width            int32   `protobuf:"zigzag32,10,opt,name=Width,json=width,proto3" json:"Width,omitempty"`
	Fps              float32 `protobuf:"fixed32,11,opt,name=Fps,json=fps,proto3" json:"Fps,omitempty"`
	Id3Tag           string  `protobuf:"bytes,12,opt,name=Id3Tag,json=id3Tag,proto3" json:"Id3Tag,omitempty"`
}

func (x *TestTagsData) Reset() {
	*x = TestTagsData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testprotos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestTagsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTagsData) ProtoMessage() {}

func (x *TestTagsData) ProtoReflect() protoreflect.Message {
	mi := &file_testprotos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTagsData.ProtoReflect.Descriptor instead.
func (*TestTagsData) Descriptor() ([]byte, []int) {
	return file_testprotos_proto_rawDescGZIP(), []int{3}
}

func (x *TestTagsData) GetUploadFile() string {
	if x != nil {
		return x.UploadFile
	}
	return ""
}

func (x *TestTagsData) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

func (x *TestTagsData) GetMetadataOnly() string {
	if x != nil {
		return x.MetadataOnly
	}
	return ""
}

func (x *TestTagsData) GetContentTypeId() int64 {
	if x != nil {
		return x.ContentTypeId
	}
	return 0
}

func (x *TestTagsData) GetCreativeApiId() int64 {
	if x != nil {
		return x.CreativeApiId
	}
	return 0
}

func (x *TestTagsData) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TestTagsData) GetPhysicalDuration() float32 {
	if x != nil {
		return x.PhysicalDuration
	}
	return 0
}

func (x *TestTagsData) GetBitrate() int32 {
	if x != nil {
		return x.Bitrate
	}
	return 0
}

func (x *TestTagsData) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TestTagsData) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *TestTagsData) GetFps() float32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *TestTagsData) GetId3Tag() string {
	if x != nil {
		return x.Id3Tag
	}
	return ""
}

var File_testprotos_proto protoreflect.FileDescriptor

var file_testprotos_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x65, 0x73, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x74, 0x75, 0x72, 0x62, 0x6f, 0x22, 0xfa, 0x01, 0x0a, 0x0e, 0x54, 0x65,
	0x73, 0x74, 0x50, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a,
	0x49, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x49, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11,
	0x52, 0x0a, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x55, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0b, 0x75, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x55, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0b, 0x75, 0x69, 0x6e, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x22, 0x0a, 0x0c, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0c, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x33, 0x32, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x36, 0x34, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x66, 0x6c, 0x6f, 0x61,
	0x74, 0x36, 0x34, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x42, 0x6f, 0x6f, 0x6c,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x62, 0x6f, 0x6f,
	0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x27, 0x0a, 0x0f, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x33, 0x0a, 0x08, 0x54, 0x65, 0x73, 0x74, 0x54, 0x61, 0x67, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x75, 0x72, 0x62,
	0x6f, 0x2e, 0x54, 0x65, 0x73, 0x74, 0x54, 0x61, 0x67, 0x73, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0xf6, 0x02, 0x0a, 0x0c, 0x54, 0x65, 0x73, 0x74, 0x54, 0x61, 0x67,
	0x73, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46,
	0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x70, 0x6c, 0x6f, 0x61,
	0x64, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x55,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x55, 0x72, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x4f,
	0x6e, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x12, 0x24, 0x0a,
	0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x69, 0x76, 0x65, 0x41, 0x70, 0x69, 0x49, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x76, 0x65, 0x41, 0x70,
	0x69, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x11, 0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2a, 0x0a, 0x10, 0x50, 0x68, 0x79, 0x73, 0x69, 0x63, 0x61, 0x6c, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x10, 0x70, 0x68, 0x79, 0x73, 0x69,
	0x63, 0x61, 0x6c, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x42,
	0x69, 0x74, 0x72, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x11, 0x52, 0x07, 0x62, 0x69,
	0x74, 0x72, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x11, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x11, 0x52, 0x05, 0x77, 0x69,
	0x64, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x46, 0x70, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x03, 0x66, 0x70, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x64, 0x33, 0x54, 0x61, 0x67, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x64, 0x33, 0x54, 0x61, 0x67, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testprotos_proto_rawDescOnce sync.Once
	file_testprotos_proto_rawDescData = file_testprotos_proto_rawDesc
)

func file_testprotos_proto_rawDescGZIP() []byte {
	file_testprotos_proto_rawDescOnce.Do(func() {
		file_testprotos_proto_rawDescData = protoimpl.X.CompressGZIP(file_testprotos_proto_rawDescData)
	})
	return file_testprotos_proto_rawDescData
}

var file_testprotos_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_testprotos_proto_goTypes = []interface{}{
	(*TestPrimitives)(nil),  // 0: turbo.TestPrimitives
	(*TestProtoStruct)(nil), // 1: turbo.TestProtoStruct
	(*TestTags)(nil),        // 2: turbo.TestTags
	(*TestTagsData)(nil),    // 3: turbo.TestTagsData
}
var file_testprotos_proto_depIdxs = []int32{
	3, // 0: turbo.TestTags.Data:type_name -> turbo.TestTagsData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_testprotos_proto_init() }
func file_testprotos_proto_init() {
	if File_testprotos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testprotos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestPrimitives); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testprotos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestProtoStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testprotos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestTags); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testprotos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestTagsData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testprotos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testprotos_proto_goTypes,
		DependencyIndexes: file_testprotos_proto_depIdxs,
		MessageInfos:      file_testprotos_proto_msgTypes,
	}.Build()
	File_testprotos_proto = out.File
	file_testprotos_proto_rawDesc = nil
	file_testprotos_proto_goTypes = nil
	file_testprotos_proto_depIdxs = nil
}
