// Code generated by protoc-gen-go.
// source: inventoryservice.proto
// DO NOT EDIT!

/*
Package inventoryservice is a generated protocol buffer package.

It is generated from these files:
	inventoryservice.proto

It has these top-level messages:
	Video
	GetVideoListRequest
	GetVideoListResponse
	GetVideoRequest
	GetVideoResponse
*/
package inventoryservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Video struct {
	Id   int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *Video) Reset()                    { *m = Video{} }
func (m *Video) String() string            { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()               {}
func (*Video) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Video) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Video) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetVideoListRequest struct {
	NetworkId string `protobuf:"bytes,1,opt,name=networkId" json:"networkId,omitempty"`
}

func (m *GetVideoListRequest) Reset()                    { *m = GetVideoListRequest{} }
func (m *GetVideoListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetVideoListRequest) ProtoMessage()               {}
func (*GetVideoListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetVideoListRequest) GetNetworkId() string {
	if m != nil {
		return m.NetworkId
	}
	return ""
}

type GetVideoListResponse struct {
	Videos []*Video `protobuf:"bytes,1,rep,name=videos" json:"videos,omitempty"`
}

func (m *GetVideoListResponse) Reset()                    { *m = GetVideoListResponse{} }
func (m *GetVideoListResponse) String() string            { return proto.CompactTextString(m) }
func (*GetVideoListResponse) ProtoMessage()               {}
func (*GetVideoListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetVideoListResponse) GetVideos() []*Video {
	if m != nil {
		return m.Videos
	}
	return nil
}

type GetVideoRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetVideoRequest) Reset()                    { *m = GetVideoRequest{} }
func (m *GetVideoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetVideoRequest) ProtoMessage()               {}
func (*GetVideoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetVideoRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetVideoResponse struct {
	Video *Video `protobuf:"bytes,1,opt,name=video" json:"video,omitempty"`
}

func (m *GetVideoResponse) Reset()                    { *m = GetVideoResponse{} }
func (m *GetVideoResponse) String() string            { return proto.CompactTextString(m) }
func (*GetVideoResponse) ProtoMessage()               {}
func (*GetVideoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetVideoResponse) GetVideo() *Video {
	if m != nil {
		return m.Video
	}
	return nil
}

func init() {
	proto.RegisterType((*Video)(nil), "Video")
	proto.RegisterType((*GetVideoListRequest)(nil), "GetVideoListRequest")
	proto.RegisterType((*GetVideoListResponse)(nil), "GetVideoListResponse")
	proto.RegisterType((*GetVideoRequest)(nil), "GetVideoRequest")
	proto.RegisterType((*GetVideoResponse)(nil), "GetVideoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for InventoryService service

type InventoryServiceClient interface {
	GetVideoList(ctx context.Context, in *GetVideoListRequest, opts ...grpc.CallOption) (*GetVideoListResponse, error)
	GetVideo(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*GetVideoResponse, error)
}

type inventoryServiceClient struct {
	cc *grpc.ClientConn
}

func NewInventoryServiceClient(cc *grpc.ClientConn) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) GetVideoList(ctx context.Context, in *GetVideoListRequest, opts ...grpc.CallOption) (*GetVideoListResponse, error) {
	out := new(GetVideoListResponse)
	err := grpc.Invoke(ctx, "/InventoryService/getVideoList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetVideo(ctx context.Context, in *GetVideoRequest, opts ...grpc.CallOption) (*GetVideoResponse, error) {
	out := new(GetVideoResponse)
	err := grpc.Invoke(ctx, "/InventoryService/getVideo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for InventoryService service

type InventoryServiceServer interface {
	GetVideoList(context.Context, *GetVideoListRequest) (*GetVideoListResponse, error)
	GetVideo(context.Context, *GetVideoRequest) (*GetVideoResponse, error)
}

func RegisterInventoryServiceServer(s *grpc.Server, srv InventoryServiceServer) {
	s.RegisterService(&_InventoryService_serviceDesc, srv)
}

func _InventoryService_GetVideoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetVideoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/InventoryService/GetVideoList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetVideoList(ctx, req.(*GetVideoListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetVideo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVideoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetVideo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/InventoryService/GetVideo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetVideo(ctx, req.(*GetVideoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InventoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getVideoList",
			Handler:    _InventoryService_GetVideoList_Handler,
		},
		{
			MethodName: "getVideo",
			Handler:    _InventoryService_GetVideo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventoryservice.proto",
}

func init() { proto.RegisterFile("inventoryservice.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x14, 0x84, 0x9b, 0xad, 0x5d, 0xdc, 0xa7, 0xe8, 0xfa, 0xac, 0xb2, 0x94, 0x22, 0x6b, 0x4e, 0x0b,
	0x42, 0xd0, 0x16, 0xbc, 0x79, 0x96, 0x82, 0xa7, 0x08, 0xde, 0xd5, 0x7d, 0x48, 0x10, 0x93, 0x9a,
	0xc4, 0x15, 0xef, 0xfe, 0x70, 0x69, 0xb6, 0x21, 0xb6, 0xf4, 0x16, 0x86, 0x99, 0xc9, 0xf7, 0x06,
	0xce, 0x95, 0xee, 0x48, 0x7b, 0x63, 0x7f, 0x1c, 0xd9, 0x4e, 0xbd, 0x92, 0x58, 0x5a, 0xe3, 0x0d,
	0xbf, 0x82, 0xd1, 0x93, 0x6a, 0xc9, 0xe0, 0x11, 0x64, 0xaa, 0xad, 0x58, 0xcd, 0x9a, 0xa1, 0xcc,
	0x54, 0x8b, 0x08, 0x7b, 0xfa, 0xf9, 0x83, 0xaa, 0xac, 0x66, 0x4d, 0x21, 0xc3, 0x9b, 0xcf, 0xe1,
	0xf4, 0x9e, 0x7c, 0xf0, 0x3f, 0x28, 0xe7, 0x25, 0x7d, 0x7e, 0x91, 0xf3, 0x38, 0x85, 0x42, 0x93,
	0xff, 0x36, 0xf6, 0x7d, 0xd1, 0x37, 0x14, 0x32, 0x09, 0xfc, 0x16, 0xc6, 0x9b, 0x21, 0xb7, 0x34,
	0xda, 0x11, 0x5e, 0x40, 0xde, 0xad, 0x44, 0x57, 0xb1, 0x7a, 0xd8, 0x1c, 0xcc, 0x72, 0x11, 0x3c,
	0x72, 0xad, 0xf2, 0x4b, 0x38, 0x8e, 0xb9, 0xf8, 0x51, 0x62, 0x2c, 0x56, 0x8c, 0xfc, 0x1a, 0xca,
	0x64, 0x59, 0xd7, 0x4e, 0x61, 0x14, 0x0a, 0x82, 0x2d, 0xb5, 0xf6, 0xe2, 0xec, 0x97, 0x41, 0xb9,
	0x88, 0x4b, 0x3c, 0xf6, 0x4b, 0xe0, 0x1d, 0x1c, 0xbe, 0xfd, 0x23, 0xc4, 0xb1, 0xd8, 0x71, 0xe5,
	0xe4, 0x4c, 0xec, 0x3a, 0x83, 0x0f, 0xf0, 0x06, 0xf6, 0x63, 0x1c, 0x4b, 0xb1, 0xc5, 0x3c, 0x39,
	0x11, 0xdb, 0x88, 0x7c, 0xf0, 0x92, 0x87, 0xf1, 0xe7, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83,
	0x6d, 0x9b, 0x6a, 0x96, 0x01, 0x00, 0x00,
}
